
-- 제약조건(DDL 작성)
-- 1. NOT NULL
CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
    );
    
INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD)
VALUES('HONG1234', 'HONG1234');

INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD)
VALUES('KANG1234', NULL);

UPDATE TABLE_NOTNULL SET login_pwd = NULL WHERE login_id='HONG1234';

SELECT * FROM TABLE_NOTNULL;

-- 제약조건 확인하기
SELECT * FROM user_constraints;

-- 제약조건명 지정하기
CREATE TABLE TABLE_NOTNULL2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBL_NN_LOGIND_NN NOT NULL,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBL_NN_LOGINPWD_NN NOT NULL,
    TEL VARCHAR2(20)
    );
    SELECT * FROM user_constraints;
    
-- 제약조건 추가
ALTER TABLE TABLE_NOTNULL2 MODIFY(TEL NOT NULL);

-- 제약조건 이름 추가 시
ALTER TABLE TABLE_NOTNULL2 MODIFY(TEL CONSTRAINT TBL_NN_TEL_NN NOT NULL);
-- 제약조건 이름 변경
ALTER TABLE TABLE_NOTNULL2 RENAME CONSTRAINT SYS_C0012158 TO TBL_NN_TEL_NN;

-- 제약조건 삭제
ALTER TABLE TABLE_NOTNULL2 DROP CONSTRAINT TBL_NN_TEL_NN;

-- 사전에 NULL값이 들어간 필드가 있을 경우 UPDATE 불가
UPDATE TABLE_NOTNULL SET TEL = '010-1111-2222' WHERE LOGIN_ID = 'HONG1234';
ALTER TABLE TABLE_NOTNULL MODIFY(TEL NOT NULL);

